### Vavariables
@url_dev = http://localhost:3000/v1/api

### signup

POST {{url_dev}}/signup
Content-Type: application/json

{
    "name": "Nguyen Van A",
    "email": "nguyenvana@gmail.com",
    "password": "123456"
}